apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: k8s-learning
  labels:
    app: frontend
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: kubernetes-concepts-demo
spec:
  selector:
    app: frontend
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 43000
      targetPort: 43000
      nodePort: 43080
  type: NodePort

